# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Java version required to build and run this mod
java_version=25

# Fabric Properties
minecraft_version = 26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version = 2.0.2
maven_group = net.alfonsormadrid
archives_base_name = enchant-transfer-mod

# Dependencies
fabric_version=0.158.0+26.2
